version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GO_ENV=development
    restart: unless-stopped

  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend
